public without sharing class HeatMapWrapper {
	public Account account{get;set;}
	public String colorURL{get;set;}
	public Decimal adjustedTotal{get;set;}
	public Decimal autoTotal{get;set;}
	public Decimal contractROIScore{get;set;}
	public Decimal proratedROIScore{get;set;}
	public Decimal ROITotal{get;set;}
	public Decimal renewalScore{get;set;}
	public Decimal dismissalsScore{get;set;}
	public Decimal twelveMonthROIScore{get;set;}
	public Decimal mostRecentOM_Score{get;set;}
	public Decimal mostRecentLitScore{get;set;}
	public Decimal recencyTotal{get;set;}
	public Decimal rateScore{get;set;} 
}